insert into districts (dis_name) values ('Aveiro');
insert into districts (dis_name) values ('Beja');
insert into districts (dis_name) values ('Braga');
insert into districts (dis_name) values ('Bragança');
insert into districts (dis_name) values ('Castelo Branco');
insert into districts (dis_name) values ('Coimbra');
insert into districts (dis_name) values ('Évora');
insert into districts (dis_name) values ('Faro');
insert into districts (dis_name) values ('Guarda');
insert into districts (dis_name) values ('Leiria');
insert into districts (dis_name) values ('Lisboa');
insert into districts (dis_name) values ('Portalegre');
insert into districts (dis_name) values ('Porto');
insert into districts (dis_name) values ('Santarém');
insert into districts (dis_name) values ('Setúbal');
insert into districts (dis_name) values ('Viana do Castelo');
insert into districts (dis_name) values ('Vila Real');
insert into districts (dis_name) values ('Viseu');
insert into districts (dis_name) values ('Azores');
insert into districts (dis_name) values ('Madeira');

insert into cities (city_name, city_dis_id) values ('Águeda', 1);
insert into cities (city_name, city_dis_id) values ('Albergaria-a-Velha', 1);
insert into cities (city_name, city_dis_id) values ('Anadia', 1);
insert into cities (city_name, city_dis_id) values ('Arouca', 1);
insert into cities (city_name, city_dis_id) values ('Aveiro', 1);
insert into cities (city_name, city_dis_id) values ('Castelo de Paiva', 1);
insert into cities (city_name, city_dis_id) values ('Espinho', 1);
insert into cities (city_name, city_dis_id) values ('Estarreja', 1);
insert into cities (city_name, city_dis_id) values ('Ílhavo', 1);
insert into cities (city_name, city_dis_id) values ('Mealhada', 1);
insert into cities (city_name, city_dis_id) values ('Murtosa', 1);
insert into cities (city_name, city_dis_id) values ('Oliveira de Azeméis', 1);
insert into cities (city_name, city_dis_id) values ('Oliveira do Bairro', 1);
insert into cities (city_name, city_dis_id) values ('Ovar', 1);
insert into cities (city_name, city_dis_id) values ('Santa Maria da Feira', 1);
insert into cities (city_name, city_dis_id) values ('São João da Madeira', 1);
insert into cities (city_name, city_dis_id) values ('Sever do Vouga', 1);
insert into cities (city_name, city_dis_id) values ('Vagos', 1);
insert into cities (city_name, city_dis_id) values ('Vale de Cambra', 1);
insert into cities (city_name, city_dis_id) values ('Aljustrel', 2);
insert into cities (city_name, city_dis_id) values ('Almodôvar', 2);
insert into cities (city_name, city_dis_id) values ('Alvito', 2);
insert into cities (city_name, city_dis_id) values ('Barrancos', 2);
insert into cities (city_name, city_dis_id) values ('Beja', 2);
insert into cities (city_name, city_dis_id) values ('Castro Verde', 2);
insert into cities (city_name, city_dis_id) values ('Cuba', 2);
insert into cities (city_name, city_dis_id) values ('Ferreira do Alentejo', 2);
insert into cities (city_name, city_dis_id) values ('Mértola', 2);
insert into cities (city_name, city_dis_id) values ('Moura', 2);
insert into cities (city_name, city_dis_id) values ('Odemira', 2);
insert into cities (city_name, city_dis_id) values ('Ourique', 2);
insert into cities (city_name, city_dis_id) values ('Serpa', 2);
insert into cities (city_name, city_dis_id) values ('Vidigueira', 2);
insert into cities (city_name, city_dis_id) values ('Amares', 3);
insert into cities (city_name, city_dis_id) values ('Barcelos', 3);
insert into cities (city_name, city_dis_id) values ('Braga', 3);
insert into cities (city_name, city_dis_id) values ('Cabeceiras de Basto', 3);
insert into cities (city_name, city_dis_id) values ('Celorico de Basto', 3);
insert into cities (city_name, city_dis_id) values ('Esposende', 3);
insert into cities (city_name, city_dis_id) values ('Fafe', 3);
insert into cities (city_name, city_dis_id) values ('Guimarães', 3);
insert into cities (city_name, city_dis_id) values ('Póvoa de Lanhoso', 3);
insert into cities (city_name, city_dis_id) values ('Terras de Bouro', 3);
insert into cities (city_name, city_dis_id) values ('Vieira do Minho', 3);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Famalicão', 3);
insert into cities (city_name, city_dis_id) values ('Vila Verde', 3);
insert into cities (city_name, city_dis_id) values ('Vizela', 3);
insert into cities (city_name, city_dis_id) values ('Alfândega da Fé', 4);
insert into cities (city_name, city_dis_id) values ('Bragança', 4);
insert into cities (city_name, city_dis_id) values ('Carrazeda de Ansiães', 4);
insert into cities (city_name, city_dis_id) values ('Freixo de Espada à Cinta', 4);
insert into cities (city_name, city_dis_id) values ('Macedo de Cavaleiros', 4);
insert into cities (city_name, city_dis_id) values ('Miranda do Douro', 4);
insert into cities (city_name, city_dis_id) values ('Mirandela', 4);
insert into cities (city_name, city_dis_id) values ('Mogadouro', 4);
insert into cities (city_name, city_dis_id) values ('Torre de Moncorvo', 4);
insert into cities (city_name, city_dis_id) values ('Vila Flor', 4);
insert into cities (city_name, city_dis_id) values ('Vimioso', 4);
insert into cities (city_name, city_dis_id) values ('Vinhais', 4);
insert into cities (city_name, city_dis_id) values ('Belmonte', 5);
insert into cities (city_name, city_dis_id) values ('Castelo Branco', 5);
insert into cities (city_name, city_dis_id) values ('Covilhã', 5);
insert into cities (city_name, city_dis_id) values ('Fundão', 5);
insert into cities (city_name, city_dis_id) values ('Idanha-a-Nova', 5);
insert into cities (city_name, city_dis_id) values ('Oleiros', 5);
insert into cities (city_name, city_dis_id) values ('Penamacor', 5);
insert into cities (city_name, city_dis_id) values ('Proença-a-Nova', 5);
insert into cities (city_name, city_dis_id) values ('Sertã', 5);
insert into cities (city_name, city_dis_id) values ('Vila de Rei', 5);
insert into cities (city_name, city_dis_id) values ('Vila Velha de Ródão', 5);
insert into cities (city_name, city_dis_id) values ('Arganil', 6);
insert into cities (city_name, city_dis_id) values ('Cantanhede', 6);
insert into cities (city_name, city_dis_id) values ('Coimbra', 6);
insert into cities (city_name, city_dis_id) values ('Condeixa-a-Nova', 6);
insert into cities (city_name, city_dis_id) values ('Figueira da Foz', 6);
insert into cities (city_name, city_dis_id) values ('Góis', 6);
insert into cities (city_name, city_dis_id) values ('Lousã', 6);
insert into cities (city_name, city_dis_id) values ('Mira', 6);
insert into cities (city_name, city_dis_id) values ('Miranda do Corvo', 6);
insert into cities (city_name, city_dis_id) values ('Montemor-o-Velho', 6);
insert into cities (city_name, city_dis_id) values ('Oliveira do Hospital', 6);
insert into cities (city_name, city_dis_id) values ('Pampilhosa da Serra', 6);
insert into cities (city_name, city_dis_id) values ('Penacova', 6);
insert into cities (city_name, city_dis_id) values ('Penela', 6);
insert into cities (city_name, city_dis_id) values ('Soure', 6);
insert into cities (city_name, city_dis_id) values ('Tábua', 6);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Poiares', 6);
insert into cities (city_name, city_dis_id) values ('Alandroal', 7);
insert into cities (city_name, city_dis_id) values ('Arraiolos', 7);
insert into cities (city_name, city_dis_id) values ('Borba', 7);
insert into cities (city_name, city_dis_id) values ('Estremoz', 7);
insert into cities (city_name, city_dis_id) values ('Évora', 7);
insert into cities (city_name, city_dis_id) values ('Montemor-o-Novo', 7);
insert into cities (city_name, city_dis_id) values ('Mora', 7);
insert into cities (city_name, city_dis_id) values ('Mourão', 7);
insert into cities (city_name, city_dis_id) values ('Portel', 7);
insert into cities (city_name, city_dis_id) values ('Redondo', 7);
insert into cities (city_name, city_dis_id) values ('Reguengos de Monsaraz', 7);
insert into cities (city_name, city_dis_id) values ('Vendas Novas', 7);
insert into cities (city_name, city_dis_id) values ('Viana do Alentejo', 7);
insert into cities (city_name, city_dis_id) values ('Vila Viçosa', 7);
insert into cities (city_name, city_dis_id) values ('Albufeira', 8);
insert into cities (city_name, city_dis_id) values ('Alcoutim', 8);
insert into cities (city_name, city_dis_id) values ('Aljezur', 8);
insert into cities (city_name, city_dis_id) values ('Castro Marim', 8);
insert into cities (city_name, city_dis_id) values ('Faro', 8);
insert into cities (city_name, city_dis_id) values ('Lagoa', 8);
insert into cities (city_name, city_dis_id) values ('Lagos', 8);
insert into cities (city_name, city_dis_id) values ('Loulé', 8);
insert into cities (city_name, city_dis_id) values ('Monchique', 8);
insert into cities (city_name, city_dis_id) values ('Olhão', 8);
insert into cities (city_name, city_dis_id) values ('Portimão', 8);
insert into cities (city_name, city_dis_id) values ('São Brás de Alportel', 8);
insert into cities (city_name, city_dis_id) values ('Silves', 8);
insert into cities (city_name, city_dis_id) values ('Tavira', 8);
insert into cities (city_name, city_dis_id) values ('Vila do Bispo', 8);
insert into cities (city_name, city_dis_id) values ('Vila Real de Santo António', 8);
insert into cities (city_name, city_dis_id) values ('Aguiar da Beira', 9);
insert into cities (city_name, city_dis_id) values ('Almeida', 9);
insert into cities (city_name, city_dis_id) values ('Celorico da Beira', 9);
insert into cities (city_name, city_dis_id) values ('Figueira de Castelo Rodrigo', 9);
insert into cities (city_name, city_dis_id) values ('Fornos de Algodres', 9);
insert into cities (city_name, city_dis_id) values ('Gouveia', 9);
insert into cities (city_name, city_dis_id) values ('Guarda', 9);
insert into cities (city_name, city_dis_id) values ('Manteigas', 9);
insert into cities (city_name, city_dis_id) values ('Mêda', 9);
insert into cities (city_name, city_dis_id) values ('Pinhel', 9);
insert into cities (city_name, city_dis_id) values ('Sabugal', 9);
insert into cities (city_name, city_dis_id) values ('Seia', 9);
insert into cities (city_name, city_dis_id) values ('Trancoso', 9);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Foz Côa', 9);
insert into cities (city_name, city_dis_id) values ('Alcobaça', 10);
insert into cities (city_name, city_dis_id) values ('Alvaiázere', 10);
insert into cities (city_name, city_dis_id) values ('Ansião', 10);
insert into cities (city_name, city_dis_id) values ('Batalha', 10);
insert into cities (city_name, city_dis_id) values ('Bombarral', 10);
insert into cities (city_name, city_dis_id) values ('Caldas da Rainha', 10);
insert into cities (city_name, city_dis_id) values ('Castanheira de Pera', 10);
insert into cities (city_name, city_dis_id) values ('Figueiró dos Vinhos', 10);
insert into cities (city_name, city_dis_id) values ('Leiria', 10);
insert into cities (city_name, city_dis_id) values ('Marinha Grande', 10);
insert into cities (city_name, city_dis_id) values ('Nazaré', 10);
insert into cities (city_name, city_dis_id) values ('Óbidos', 10);
insert into cities (city_name, city_dis_id) values ('Pedrógão Grande', 10);
insert into cities (city_name, city_dis_id) values ('Peniche', 10);
insert into cities (city_name, city_dis_id) values ('Pombal', 10);
insert into cities (city_name, city_dis_id) values ('Porto de Mós', 10);
insert into cities (city_name, city_dis_id) values ('Alenquer', 11);
insert into cities (city_name, city_dis_id) values ('Amadora', 11);
insert into cities (city_name, city_dis_id) values ('Arruda dos Vinhos', 11);
insert into cities (city_name, city_dis_id) values ('Azambuja', 11);
insert into cities (city_name, city_dis_id) values ('Cadaval', 11);
insert into cities (city_name, city_dis_id) values ('Cascais', 11);
insert into cities (city_name, city_dis_id) values ('Lisboa', 11);
insert into cities (city_name, city_dis_id) values ('Loures', 11);
insert into cities (city_name, city_dis_id) values ('Lourinhã', 11);
insert into cities (city_name, city_dis_id) values ('Mafra', 11);
insert into cities (city_name, city_dis_id) values ('Odivelas', 11);
insert into cities (city_name, city_dis_id) values ('Oeiras', 11);
insert into cities (city_name, city_dis_id) values ('Sintra', 11);
insert into cities (city_name, city_dis_id) values ('Sobral de Monte Agraço', 11);
insert into cities (city_name, city_dis_id) values ('Torres Vedras', 11);
insert into cities (city_name, city_dis_id) values ('Vila Franca de Xira', 11);
insert into cities (city_name, city_dis_id) values ('Alter do Chão', 12);
insert into cities (city_name, city_dis_id) values ('Arronches', 12);
insert into cities (city_name, city_dis_id) values ('Avis', 12);
insert into cities (city_name, city_dis_id) values ('Campo Maior', 12);
insert into cities (city_name, city_dis_id) values ('Castelo de Vide', 12);
insert into cities (city_name, city_dis_id) values ('Crato', 12);
insert into cities (city_name, city_dis_id) values ('Elvas', 12);
insert into cities (city_name, city_dis_id) values ('Fronteira', 12);
insert into cities (city_name, city_dis_id) values ('Gavião', 12);
insert into cities (city_name, city_dis_id) values ('Marvão', 12);
insert into cities (city_name, city_dis_id) values ('Monforte', 12);
insert into cities (city_name, city_dis_id) values ('Nisa', 12);
insert into cities (city_name, city_dis_id) values ('Ponte de Sor', 12);
insert into cities (city_name, city_dis_id) values ('Portalegre', 12);
insert into cities (city_name, city_dis_id) values ('Sousel', 12);
insert into cities (city_name, city_dis_id) values ('Amarante', 13);
insert into cities (city_name, city_dis_id) values ('Baião', 13);
insert into cities (city_name, city_dis_id) values ('Felgueiras', 13);
insert into cities (city_name, city_dis_id) values ('Gondomar', 13);
insert into cities (city_name, city_dis_id) values ('Lousada', 13);
insert into cities (city_name, city_dis_id) values ('Maia', 13);
insert into cities (city_name, city_dis_id) values ('Marco de Canaveses', 13);
insert into cities (city_name, city_dis_id) values ('Matosinhos', 13);
insert into cities (city_name, city_dis_id) values ('Paços de Ferreira', 13);
insert into cities (city_name, city_dis_id) values ('Paredes', 13);
insert into cities (city_name, city_dis_id) values ('Penafiel', 13);
insert into cities (city_name, city_dis_id) values ('Porto', 13);
insert into cities (city_name, city_dis_id) values ('Póvoa de Varzim', 13);
insert into cities (city_name, city_dis_id) values ('Santo Tirso', 13);
insert into cities (city_name, city_dis_id) values ('Trofa', 13);
insert into cities (city_name, city_dis_id) values ('Valongo', 13);
insert into cities (city_name, city_dis_id) values ('Vila do Conde', 13);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Gaia', 13);
insert into cities (city_name, city_dis_id) values ('Abrantes', 14);
insert into cities (city_name, city_dis_id) values ('Alcanena', 14);
insert into cities (city_name, city_dis_id) values ('Almeirim', 14);
insert into cities (city_name, city_dis_id) values ('Alpiarça', 14);
insert into cities (city_name, city_dis_id) values ('Benavente', 14);
insert into cities (city_name, city_dis_id) values ('Cartaxo', 14);
insert into cities (city_name, city_dis_id) values ('Chamusca', 14);
insert into cities (city_name, city_dis_id) values ('Constância', 14);
insert into cities (city_name, city_dis_id) values ('Coruche', 14);
insert into cities (city_name, city_dis_id) values ('Entroncamento', 14);
insert into cities (city_name, city_dis_id) values ('Ferreira do Zêzere', 14);
insert into cities (city_name, city_dis_id) values ('Golegã', 14);
insert into cities (city_name, city_dis_id) values ('Mação', 14);
insert into cities (city_name, city_dis_id) values ('Ourém', 14);
insert into cities (city_name, city_dis_id) values ('Rio Maior', 14);
insert into cities (city_name, city_dis_id) values ('Salvaterra de Magos', 14);
insert into cities (city_name, city_dis_id) values ('Santarém', 14);
insert into cities (city_name, city_dis_id) values ('Sardoal', 14);
insert into cities (city_name, city_dis_id) values ('Tomar', 14);
insert into cities (city_name, city_dis_id) values ('Torres Novas', 14);
insert into cities (city_name, city_dis_id) values ('Vila Nova da Barquinha', 14);
insert into cities (city_name, city_dis_id) values ('Alcácer do Sal', 15);
insert into cities (city_name, city_dis_id) values ('Alcochete', 15);
insert into cities (city_name, city_dis_id) values ('Almada', 15);
insert into cities (city_name, city_dis_id) values ('Barreiro', 15);
insert into cities (city_name, city_dis_id) values ('Grândola', 15);
insert into cities (city_name, city_dis_id) values ('Moita', 15);
insert into cities (city_name, city_dis_id) values ('Montijo', 15);
insert into cities (city_name, city_dis_id) values ('Palmela', 15);
insert into cities (city_name, city_dis_id) values ('Santiago do Cacém', 15);
insert into cities (city_name, city_dis_id) values ('Seixal', 15);
insert into cities (city_name, city_dis_id) values ('Sesimbra', 15);
insert into cities (city_name, city_dis_id) values ('Setúbal', 15);
insert into cities (city_name, city_dis_id) values ('Sines', 15);
insert into cities (city_name, city_dis_id) values ('Arcos de Valdevez', 16);
insert into cities (city_name, city_dis_id) values ('Caminha', 16);
insert into cities (city_name, city_dis_id) values ('Melgaço', 16);
insert into cities (city_name, city_dis_id) values ('Monção', 16);
insert into cities (city_name, city_dis_id) values ('Paredes de Coura', 16);
insert into cities (city_name, city_dis_id) values ('Ponte da Barca', 16);
insert into cities (city_name, city_dis_id) values ('Ponte de Lima', 16);
insert into cities (city_name, city_dis_id) values ('Valença', 16);
insert into cities (city_name, city_dis_id) values ('Viana do Castelo', 16);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Cerveira', 16);
insert into cities (city_name, city_dis_id) values ('Alijó', 17);
insert into cities (city_name, city_dis_id) values ('Boticas', 17);
insert into cities (city_name, city_dis_id) values ('Chaves', 17);
insert into cities (city_name, city_dis_id) values ('Mesão Frio', 17);
insert into cities (city_name, city_dis_id) values ('Mondim de Basto', 17);
insert into cities (city_name, city_dis_id) values ('Montalegre', 17);
insert into cities (city_name, city_dis_id) values ('Murça', 17);
insert into cities (city_name, city_dis_id) values ('Peso da Régua', 17);
insert into cities (city_name, city_dis_id) values ('Ribeira de Pena', 17);
insert into cities (city_name, city_dis_id) values ('Sabrosa', 17);
insert into cities (city_name, city_dis_id) values ('Santa Marta de Penaguião', 17);
insert into cities (city_name, city_dis_id) values ('Valpaços', 17);
insert into cities (city_name, city_dis_id) values ('Vila Pouca de Aguiar', 17);
insert into cities (city_name, city_dis_id) values ('Vila Real', 17);
insert into cities (city_name, city_dis_id) values ('Armamar', 18);
insert into cities (city_name, city_dis_id) values ('Carregal do Sal', 18);
insert into cities (city_name, city_dis_id) values ('Castro Daire', 18);
insert into cities (city_name, city_dis_id) values ('Cinfães', 18);
insert into cities (city_name, city_dis_id) values ('Lamego', 18);
insert into cities (city_name, city_dis_id) values ('Mangualde', 18);
insert into cities (city_name, city_dis_id) values ('Moimenta da Beira', 18);
insert into cities (city_name, city_dis_id) values ('Mortágua', 18);
insert into cities (city_name, city_dis_id) values ('Nelas', 18);
insert into cities (city_name, city_dis_id) values ('Oliveira de Frades', 18);
insert into cities (city_name, city_dis_id) values ('Penalva do Castelo', 18);
insert into cities (city_name, city_dis_id) values ('Penedono', 18);
insert into cities (city_name, city_dis_id) values ('Resende', 18);
insert into cities (city_name, city_dis_id) values ('Santa Comba Dão', 18);
insert into cities (city_name, city_dis_id) values ('São João da Pesqueira', 18);
insert into cities (city_name, city_dis_id) values ('São Pedro do Sul', 18);
insert into cities (city_name, city_dis_id) values ('Sátão', 18);
insert into cities (city_name, city_dis_id) values ('Sernancelhe', 18);
insert into cities (city_name, city_dis_id) values ('Tabuaço', 18);
insert into cities (city_name, city_dis_id) values ('Tarouca', 18);
insert into cities (city_name, city_dis_id) values ('Tondela', 18);
insert into cities (city_name, city_dis_id) values ('Vila Nova de Paiva', 18);
insert into cities (city_name, city_dis_id) values ('Viseu', 18);
insert into cities (city_name, city_dis_id) values ('Vouzela', 18);
insert into cities (city_name, city_dis_id) values ('Angra do Heroísmo', 19);
insert into cities (city_name, city_dis_id) values ('Calheta', 19);
insert into cities (city_name, city_dis_id) values ('Vila do Corvo', 19);
insert into cities (city_name, city_dis_id) values ('Horta', 19);
insert into cities (city_name, city_dis_id) values ('Lagoa', 19);
insert into cities (city_name, city_dis_id) values ('Lajes das Flores', 19);
insert into cities (city_name, city_dis_id) values ('Lajes do Pico', 19);
insert into cities (city_name, city_dis_id) values ('Madalena', 19);
insert into cities (city_name, city_dis_id) values ('Nordeste', 19);
insert into cities (city_name, city_dis_id) values ('Ponta Delgada', 19);
insert into cities (city_name, city_dis_id) values ('Povoação', 19);
insert into cities (city_name, city_dis_id) values ('Praia da Vitória', 19);
insert into cities (city_name, city_dis_id) values ('Ribeira Grande', 19);
insert into cities (city_name, city_dis_id) values ('Santa Cruz da Graciosa', 19);
insert into cities (city_name, city_dis_id) values ('Santa Cruz das Flores', 19);
insert into cities (city_name, city_dis_id) values ('São Roque do Pico', 19);
insert into cities (city_name, city_dis_id) values ('Velas', 19);
insert into cities (city_name, city_dis_id) values ('Vila do Porto', 19);
insert into cities (city_name, city_dis_id) values ('Vila Franca do Campo', 19);
insert into cities (city_name, city_dis_id) values ('Calheta', 20);
insert into cities (city_name, city_dis_id) values ('Câmara de Lobos', 20);
insert into cities (city_name, city_dis_id) values ('Funchal', 20);
insert into cities (city_name, city_dis_id) values ('Machico', 20);
insert into cities (city_name, city_dis_id) values ('Ponta do Sol', 20);
insert into cities (city_name, city_dis_id) values ('Porto Moniz', 20);
insert into cities (city_name, city_dis_id) values ('Porto Santo', 20);
insert into cities (city_name, city_dis_id) values ('Ribeira Brava', 20);
insert into cities (city_name, city_dis_id) values ('Santa Cruz', 20);
insert into cities (city_name, city_dis_id) values ('Santana', 20);
insert into cities (city_name, city_dis_id) values ('São Vicente', 20);

insert into categories (cat_name) values ('Vestuário');
insert into categories (cat_name) values ('Lazer');
insert into categories (cat_name) values ('Telemóveis e Tablets');
insert into categories (cat_name) values ('Desporto');
insert into categories (cat_name) values ('Moveis, Casa e Jardim');
insert into categories (cat_name) values ('Tecnologia');

insert into subcategories (subc_name, subc_cat_id) values ('Roupas Masculinas', 1);
insert into subcategories (subc_name, subc_cat_id) values ('Roupas Femininas', 1);
insert into subcategories (subc_name, subc_cat_id) values ('Calçados', 1);
insert into subcategories (subc_name, subc_cat_id) values ('Brinquedos', 2);
insert into subcategories (subc_name, subc_cat_id) values ('Jogos', 2);
insert into subcategories (subc_name, subc_cat_id) values ('Livros', 2);
insert into subcategories (subc_name, subc_cat_id) values ('Instrumentos Musicais', 2);
insert into subcategories (subc_name, subc_cat_id) values ('Telemóveis', 3);
insert into subcategories (subc_name, subc_cat_id) values ('Tablets', 3);
insert into subcategories (subc_name, subc_cat_id) values ('Tablets', 3);
insert into subcategories (subc_name, subc_cat_id) values ('Bicicletas', 4);
insert into subcategories (subc_name, subc_cat_id) values ('Futebol e Futsal', 4);
insert into subcategories (subc_name, subc_cat_id) values ('Musculação e Fitness', 4);
insert into subcategories (subc_name, subc_cat_id) values ('Musculação e Fitness', 4);
insert into subcategories (subc_name, subc_cat_id) values ('Desportos de Combate', 4);
insert into subcategories (subc_name, subc_cat_id) values ('Utilidades e Decoração', 5);
insert into subcategories (subc_name, subc_cat_id) values ('Eletrodomésticos', 5);
insert into subcategories (subc_name, subc_cat_id) values ('Jardim e Bricolage', 5);
insert into subcategories (subc_name, subc_cat_id) values ('Móveis', 5);
insert into subcategories (subc_name, subc_cat_id) values ('VideoJogos - Consolas', 6);
insert into subcategories (subc_name, subc_cat_id) values ('Computadores - Informática', 6);
insert into subcategories (subc_name, subc_cat_id) values ('Eletrónica', 6);
insert into subcategories (subc_name, subc_cat_id) values ('TV, Som e Fotografia', 6);

insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Joao', 'joao@test.com', '7wT5sbobQKTYpr', 154,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Pedro', 'pedro@test.com', 'qATnbUqyfQsMm6', 154,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Marcos', 'marcos@test.com', '8j2uRwsuWqSau4', 158,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Felipe', 'felipe@test.com', 'rCvPzrRu6rrFyb', 154,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Ana', 'ana@test.com', 'Mh5NPC3Ck7FpmC', 157,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Julia', 'julia@test.com', 'vv5kyuFgQ82UKE', 155,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Rafael', 'rafael@test.com', 'mE2dFj5wk7bXZV', 154,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Tiago', 'tiago@test.com', '7Kx9fdi5dNJj6a', 160,true);
insert into users (usr_name, usr_email, usr_password, usr_city_id, usr_active) values ('Helem', 'helem@test.com', '2ZnVF7pHo66jxD', 154,true);

insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Galaxy S8', 'Telemóvel funcionando mas esta com a tela partida', 8, '2021-01-01', true, 1);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Jaqueta Masculina preta', 'Jaqueta em bom estado, tamanho M', 1, '2021-01-01', true, 2);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Sofa 2 lugares', 'Sofa de 2 lugares em bom estado para quem estiver precisando', 19, '2021-01-02', true, 3);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Tenis Nike Masculino', 'Tamanho 42, esta quase novo, nao uso', 3, '2021-01-02', true, 4);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Telefone sem fio', 'Pouco usado, esta a juntar poeira', 16, '2021-01-03', true, 5);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Guitarra Acustica', 'Estou a doar porque nao uso', 7, '2021-01-03', true, 6);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Sapato social feminino', 'Tamanha 38, cor preta, em bom estado', 3, '2021-01-04', true, 7);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Bola de Futebol', 'Nunca foi usada', 12, '2021-01-04', true, 8);
insert into adposts (ad_title, ad_description, ad_subcategory_id, ad_pub_date, ad_active, ad_owner_id) values ('Livros', 'tenho varios livros infantis para doar', 6, '2021-01-04', true, 9);

insert into chats (chat_ad_id, chat_usr_id, chat_active, chat_date) values (6, 4, true, '2020-01-03');
insert into chats (chat_ad_id, chat_usr_id, chat_active, chat_date) values (5, 9, true, '2020-01-04');
insert into chats (chat_ad_id, chat_usr_id, chat_active, chat_date) values (9, 8, true, '2020-01-05');
insert into chats (chat_ad_id, chat_usr_id, chat_active, chat_date) values (1, 7, true, '2020-01-06');

insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('ola esta disponivel?', '2020-01-03', 1, 4);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('sim esta', '2020-01-04', 1, 6);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('oi, ainda esta disponivel?', '2020-01-04', 2, 9);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('ola ja nao esta', '2020-01-04', 2, 5);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('oi tenho interesse', '2020-01-06', 4, 7);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('esta disponivel!', '2020-01-06', 4, 1);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('onde posso pegar?', '2020-01-06', 4, 7);
insert into messages (msg_text, msg_time, msg_chat_id, msg_sender_id) values ('me ligue 110044159 que marcamos', '2020-01-06', 4, 1);

insert into wishlist (wl_usr_id, wl_ad_id, wl_date, wl_active) values (1, 6, '2020-01-06', true);
insert into wishlist (wl_usr_id, wl_ad_id, wl_date, wl_active) values (1, 3, '2020-01-06', true);
insert into wishlist (wl_usr_id, wl_ad_id, wl_date, wl_active) values (3, 5, '2020-01-06', true);
insert into wishlist (wl_usr_id, wl_ad_id, wl_date, wl_active) values (7, 9, '2020-01-06', true);